### ISSUE TITLE
Build fail with EDDL-1.0.2a and ECVL v0.4.0

### ISSUE THREAD

**Issue by abadouh** [deephealthproject/use-case-pipelines#17]
For my understanding the build fail due to the change in access specifier of the class  ecvl::DLDataset.
At some point, the access specifier of the class' variables changed from public to protected, therefore, we need to add access functions for those variables.

Reproduce:
1. Build EDDL (tag 1.0.2a)
2. Build ECVL (tag v0.4.0)
3. build pipeline: 
```
cmake -DCMAKE_INSTALL_PREFIX=install -Decvl_DIR="/ecvl.v040/build/install/" -DCMAKE_CXX_FLAGS="-g -O3 -march=native -mtune=native -Ofast " -DCMAKE_C_FLAGS="-g -O3 -march=native -mtune=native -Ofast " -DDOWNLOAD_MNIST=OFF .. 
make 
```

* The build finish successfully with ECVL 0.3.5

[pipeline.log](https://github.com/deephealthproject/use-case-pipelines/files/6931592/pipeline.log)

**Comment by lauracanalini** [comment]
Hi @abadouh,
now the pipeline is updated to work with ECVL v0.4.0a, but we recommend to update ECVL to the new v0.4.1, in which some bugs are fixed.
