### ISSUE TITLE
ResNet50 is missing in the settings options

### ISSUE THREAD

**Issue by abadouh** [deephealthproject/use-case-pipelines#18]
In order to run UC12 classification training application, the code call to setting with ResNet50.

https://github.com/deephealthproject/use-case-pipelines/blob/57f9c9deaedd4048627d19004b6e6dd5bc069858/cpp/skin_lesion_classification_training.cpp#L23

As we can see below, ResNet50 is not part of the models.

https://github.com/deephealthproject/use-case-pipelines/blob/57f9c9deaedd4048627d19004b6e6dd5bc069858/cpp/utils/utils.cpp#L89

I made the changes in the source code and added the ResNet50 option.

The application now failing to build the model:
`
terminate called after throwing an instance of 'AsymmetricPaddingException'
  what():  In layer conv2d1: Padding asymmetry detected (top=2, bottom=3, left=2, right=3). The padding asymmetry is not allowed in a Conv layer, we suggest you to use an explicit padding layer before this layer to fix the asymmetry.
`

**Comment by abadouh** [comment]
In the attachment you can find fix for the padding exception.

Tested with ECVL0.4.0+EDDL1.0.2a

[resnet_model.txt](https://github.com/deephealthproject/use-case-pipelines/files/7186230/resnet_model.txt)

**Comment by lauracanalini** [comment]
Fixed in a4e6f09febd8caf6e293d1c395ec6205fa5bc355
